;; Deactivate splash screen
(setq inhibit-splash-screen t)

;; Use UTF-8 encoding
(set-language-environment "UTF-8")

;; Tabs = 4 spaces
(setq standard-indent 4)
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(setq tab-stop-list (number-sequence 4 200 4))
(setq-default c-basic-offset 4)
(global-set-key (kbd "TAB") 'tab-to-tab-stop)
(define-key global-map (kbd "RET") 'newline-and-indent)

;; No backups
(setq make-backup-files nil)

;; Hide menubar, toolbar, scrollbar
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; No bell
(setq ring-bell-function 'ignore)

;; Display time
(setq display-time-24hr-format t)
(display-time-mode t)
(setq display-time-day-and-date 1)

;; Elisp path
(add-to-list 'load-path "~/elisp")

;; Use charcoal-black color theme
(require 'color-theme)
(eval-after-load "color-theme"
  '(progn
     (color-theme-initialize)
     (color-theme-charcoal-black)))

;; Mardown mode
(autoload 'markdown-mode "markdown-mode" "Major mode for editing Markdown files" t)
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))

;; Vertical line at column 120
(require 'fill-column-indicator)
(setq fci-rule-column 120)
(define-globalized-minor-mode global-fci-mode fci-mode (lambda () (fci-mode 1)))
(global-fci-mode 1)

;; Line numbers on the left
(setq linum-format "%4d ")
(global-linum-mode 1)

;; Additional configuration generated by 'customize-face' default
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#0c1021" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "unknown" :family "DejaVu Sans Mono")))))

;; Whitespace-mode
(global-set-key (kbd "C-x w") 'whitespace-mode)
(setq whitespace-style (quote (spaces tabs newline space-mark tab-mark newline-mark)))

;; Ibuffer
(require 'ibuffer)
(global-set-key (kbd "C-x C-b") 'ibuffer)


